version: '3.1'

services:
  web:
    image: lunacircle4/java:8
    container_name: spring-petclinic
    working_dir: /root/app
    ports:
      - "3000:3000"
    volumes:
      - ./:/root/app
    stdin_open: true
    tty: true
    command:
      - /bin/bash
